create_badge_svg:
  stage: build
  image: python:3.8.0
  script:
    - echo "Generating badges"
  after_script:
    - pip install anybadge
    - commits=$(git rev-list --all --count)
    - anybadge -l commits -v $commits -f commits.svg -c green
    # - anybadge --value=MPL-2.0 -c orange -f license.svg --label=license
  artifacts:
    paths:
        - commits.svg
        # - license.svg
    when: always
    expire_in: 52 weeks
