name: network

mgmt:
  network: custom_mgmt                # management network name
  ipv4_subnet: 172.30.0.0/16       # ipv4 range

topology:
  defaults:
    kind: linux
  nodes:
    router-WAN:
      image: frrouting/frr:latest
      binds:
        - /etc/containerlab/network/router-WAN/daemons:/etc/frr/daemons
        - /etc/containerlab/network/router-WAN/frr.conf:/etc/frr/frr.conf
    router-LAN1:
      image: frrouting/frr:latest
      binds:
        - /etc/containerlab/network/router-LAN1/daemons:/etc/frr/daemons
        - /etc/containerlab/network/router-LAN1/frr.conf:/etc/frr/frr.conf
    router-LAN2:
      image: frrouting/frr:latest
      binds:
        - /etc/containerlab/network/router-LAN2/daemons:/etc/frr/daemons
        - /etc/containerlab/network/router-LAN2/frr.conf:/etc/frr/frr.conf
    router-Internet:
      image: frrouting/frr:latest
      binds:
        - /etc/containerlab/network/router-Internet/daemons:/etc/frr/daemons
        - /etc/containerlab/network/router-Internet/frr.conf:/etc/frr/frr.conf
    br-DMZ:
      image: praqma/network-multitool:latest
    br-LAN1:
      image: praqma/network-multitool:latest
    br-LAN2:
      image: praqma/network-multitool:latest
    br-Internet:
      image: praqma/network-multitool:latest
    Standalone-Client-LAN:
      image: ubuntu:latest
    alpine-Client-LAN:
      image: alpine:latest
    Attacker-LAN:
      image: alpine:latest
    Client1-LAN:
      image: praqma/network-multitool:latest
      binds:
        - /etc/containerlab/network/LANweb.sh:/LANweb.sh
    Client2-LAN:
      image: praqma/network-multitool:latest
      binds:
        - /etc/containerlab/network/LANweb.sh:/LANweb.sh
    Server1-nginx-DMZ:
      image: nginx:latest
      binds:
        - /etc/containerlab/network/DMZsite.conf:/etc/nginx/conf.d/default.conf
    Server2-alpine-DMZ:
      image: alpine:latest
    Server3-nginx-DMZ:
      image: nginx:latest
    Server4-NSD-DMZ:
      image: alpine:latest
      binds:
        - /etc/containerlab/network/nsd.conf:/etc/nsd/nsd.conf
        - /etc/containerlab/network/DMZsite.dev.zone:/etc/nsd/DMZsite.dev.zone
        - /etc/containerlab/network/httpsDMZsite.dev.zone:/etc/nsd/httpsDMZsite.dev.zone
    Server1-samba-LAN:
      image: dperson/samba
      binds:
        - /etc/containerlab/network/SMBconf.sh:/root/SMBconf.sh
    Server2-vpn-LAN:
      image: linuxserver/wireguard
      env:
        PUID: 1000
        PGID: 1000
        TZ: Europe/Amsterdam
    Client1-WANweb:
      image: alpine:latest
      binds:
        - /etc/containerlab/network/WANweb.sh:/WANweb.sh
        - /etc/containerlab/network/Cronjobs.sh:/Cronjobs.sh
    Client2-WANweb:
      image: alpine:latest
      binds:
        - /etc/containerlab/network/WANweb.sh:/WANweb.sh
        - /etc/containerlab/network/Cronjobs.sh:/Cronjobs.sh
    Client1-WANvpn:
      image: alpine:latest
    Client2-WANvpn:
      image: alpine:latest
    Attacker-WAN:
      image: python:3.7-slim
    Server1-alpine-WAN:
      image: alpine:latest

  links:

    # router links
    - endpoints: ["router-Internet:eth1", "router-WAN:eth1"]
    - endpoints: ["router-Internet:eth2", "br-Internet:eth1"]

    - endpoints: ["router-WAN:eth2", "router-LAN1:eth1"]
    - endpoints: ["router-WAN:eth3", "router-LAN2:eth1"]
    - endpoints: ["router-WAN:eth4", "br-DMZ:eth1"]

    - endpoints: ["router-LAN1:eth2", "router-LAN2:eth2"]
    - endpoints: ["router-LAN1:eth3", "br-LAN1:eth1"]
    - endpoints: ["router-LAN1:eth4", "br-LAN1:eth2"]
    - endpoints: ["router-LAN1:eth5", "br-LAN1:eth3"]

    - endpoints: ["router-LAN2:eth3", "br-LAN2:eth1"]
    - endpoints: ["router-LAN2:eth4", "br-LAN2:eth2"]


    # client and server links

    - endpoints: ["Attacker-WAN:eth1", "br-Internet:eth4"]
    - endpoints: ["Server1-alpine-WAN:eth1", "br-Internet:eth5"]

    - endpoints: ["Client1-WANweb:eth1", "br-Internet:eth6"]
    - endpoints: ["Client2-WANweb:eth1", "br-Internet:eth7"]

    - endpoints: ["Client1-WANvpn:eth1", "br-Internet:eth8"]
    - endpoints: ["Client2-WANvpn:eth1", "br-Internet:eth9"]

    - endpoints: ["Server1-nginx-DMZ:eth1", "br-DMZ:eth2"]
    - endpoints: ["Server2-alpine-DMZ:eth1", "br-DMZ:eth3"]
    - endpoints: ["Server3-nginx-DMZ:eth1", "br-DMZ:eth4"]
    - endpoints: ["Server4-NSD-DMZ:eth1", "br-DMZ:eth5"]

    - endpoints: ["Server1-samba-LAN:eth1", "br-LAN2:eth3"]
    - endpoints: ["Server2-vpn-LAN:eth1", "br-LAN2:eth4"]

    - endpoints: ["Attacker-LAN:eth1", "br-LAN1:eth4"]
    - endpoints: ["Standalone-Client-LAN:eth1", "br-LAN1:eth5"]
    - endpoints: ["alpine-Client-LAN:eth1", "br-LAN1:eth6"]

    - endpoints: ["Client1-LAN:eth1", "br-LAN1:eth7"]
    - endpoints: ["Client2-LAN:eth1", "br-LAN1:eth8"]


