---

- hosts: localhost
  roles:
    - cleanup

- hosts: localhost
  vars_prompt:
      - name: networkname
        prompt: "How should the new network be called"
        default: network
        private: no        
      - name: NumberofLANclients
        prompt: "How many LAN clients do you want to simulate?"
        default: "{{ 10 | random }}"
        private: no
      - name: NumberofWANwebclients
        prompt: "How many WAN web clients do you want to simulate?"
        default: "{{ 10 | random }}"
        private: no
      - name: NumberofWANvpnclients
        prompt: "How many WAN vpn clients do you want to simulate?"
        default: "{{ 10 | random }}"
        private: no
      - name: savefile
        prompt: "Do you want to capture the network traffic? if so, in which fileformat do you want to have it: 'json', 'pcap' or 'both'"
        default: json
        private: no
      - name: capturelimitMB
        prompt: "How many MBs may the capture files combined be?"
        default: 100
        private: no
      - name: Dockerhub_Username
        prompt: "Fill in your Dockerhub username"
        private: no
      - name: Dockerhub_Password
        prompt: "Fill in your Dockerhub password"
        private: yes
        no_log: True
  vars:
    staticinterfaces_brLan1: 6
    staticinterfaces_brInternet: 7
    staticinterfaces_brDMZ: 3
  roles:
#    - docker
#    - setup-containerlab
    - setup-topology
    - run-and-configure
    - capture
