---

- hosts: localhost
  roles:
    - 1_cleanup

- hosts: localhost
  vars_prompt:
    - name: Dockerhub_Username
      prompt: "Fill in your Dockerhub username"
      private: no
    - name: Dockerhub_Password
      prompt: "Fill in your Dockerhub password"
      private: yes
      no_log: True 
  vars:
    staticinterfaces_brLan1: 4
    staticinterfaces_brInternet: 5
    staticinterfaces_brDMZ: 5
  vars_files:
    - config.yml
  roles:
#    - 0_docker
#    - 2_setup-containerlab
    - 3_setup-topology
    - 4_run-and-configure
    - 5_capture
