---

- name: destroy topology
  become: yes
  shell: clab destroy --topo /etc/containerlab/*/*.yml
  ignore_errors: yes

- name: delete files
  become: yes
  shell: rm -r !(captures)
  args:
    chdir: /etc/containerlab/
  ignore_errors: yes

- name: delete network files
  become: yes
  shell: rm -r clab-*
  ignore_errors: yes

- name: delete network yaml
  become: yes
  shell: rm .network.yaml
  ignore_errors: yes

- name: docker logout
  become: yes
  shell: docker logout
  ignore_errors: yes

- name: Pause to get some sensitive input
  pause:
    prompt: "Stop the playbook with 'Ctrl+C' follow by 'A' if you only wanted to stop and delete the network or press enter to continue"