---

- name: Find folders to delete
  become: yes
  find:
    paths: /etc/containerlab
    file_type: directory
    excludes: 
      - "captures"
  register: folders
  ignore_errors: yes

- name: destroy topology
  become: yes
  command: clab destroy --topo {{ item.path }}/network.yml
  ignore_errors: yes
  with_items: "{{ folders['files'] }}" 

- name: Delete folders except captures
  become: yes
  file:
    path: "{{ item.path }}"
    state: absent
  with_items: "{{ folders['files'] }}"
  ignore_errors: yes

- name: delete network files
  become: yes
  shell: if [ -f clab-* ]; then rm clab-*; fi
  ignore_errors: yes

- name: delete network yaml
  become: yes
  shell: if [ -f .network.yaml ]; then rm .network.yaml; fi
  ignore_errors: yes

- name: docker logout
  become: yes
  shell: docker logout
  ignore_errors: yes

- name: Find folders to merge pcaps
  become: yes
  find:
    paths: /etc/containerlab/captures
    file_type: directory
  register: folderss
  ignore_errors: yes

- name: mergecap
  become: yes
  shell: if [ ! -f /etc/containerlab/captures/test-2022-01-19T09\:09\:23Z/*merged.pcap ]; then echo "File not found!"; else mergecap /etc/containerlab/captures/test-2022-01-19T09\:09\:23Z/*.pcap -w /etc/containerlab/captures/test-2022-01-19T09\:09\:23Z/merged.pcap; fi
  with_items: "{{ folderss['files'] }}"
  ignore_errors: yes

- name: Pause to get some sensitive input
  pause:
    prompt: "Stop the playbook with 'Ctrl+C' follow by 'A' if you only wanted to stop and delete the network or press enter to continue"