---

- name: Find folders to delete
  become: yes
  find:
    paths: /etc/containerlab
    file_type: directory
    excludes: 
      - "captures"
  register: folders
  ignore_errors: yes

- name: Destroy topology
  become: yes
  command: clab destroy --topo {{ item.path }}/network.yml
  ignore_errors: yes
  with_items: "{{ folders['files'] }}" 

- name: Delete folders except captures
  become: yes
  file:
    path: "{{ item.path }}"
    state: absent
  with_items: "{{ folders['files'] }}"
  ignore_errors: yes

- name: Delete network files
  become: yes
  shell: if compgen -G "./clab-*" > /dev/null; then rm -rf clab-*; fi
  ignore_errors: yes

- name: Delete network yaml
  become: yes
  shell: if [ -f .network.yaml ]; then rm .network.yaml; fi
  ignore_errors: yes

- name: Docker logout
  become: yes
  shell: docker logout
  ignore_errors: yes

- name: Find folders to merge pcaps
  become: yes
  find:
    paths: /etc/containerlab/captures
    file_type: directory
  register: folderss
  ignore_errors: yes

- name: Merging potential pcap's
  become: yes
  shell: if [ -f {{ item.path }}/*.json ]; then rm .network.yaml; fi
  ignore_errors: yes

- name: Exit here to not build the network 
  pause:
    prompt: "Stop the playbook with 'Ctrl+C' followed by 'A' if you only wanted to stop and delete the network or press enter to continue"


  # shell: if [[ {{ -f item.path }}/*.json]]; then echo "Json found"; elif [ ! -f {{ item.path }}/*merged.pcap ]; then mergecap {{ item.path }}/*.pcap -w {{ item.path }}/merged.pcap;  else echo "Merged.pcap already exists!";  fi
  