---

- name: install tshark
  become: yes
  apt:
    name: tshark
    state: present
    update_cache: yes

- name: Make capture directory
  become: yes
  file:
    path: /etc/containerlab/captures
    state: directory

- name: Make network specific capture directory
  become: yes
  file:
    path: /etc/containerlab/captures/{{networkname}}-{{ ansible_date_time.iso8601 }}
    state: directory

- name: Copy Capture script
  become: yes
  template:
    src: capture.sh.j2
    dest: /etc/containerlab/captures/capture.sh

- name: Change file permissions Capture script
  become: yes
  file:
    path: /etc/containerlab/captures/capture.sh
    mode: '0744'

- name: Run capture script
  become: yes
  shell: /etc/containerlab/captures/capture.sh &
