---

- name: Make Containerlab network directory
  become: yes
  file:
    path: /etc/containerlab/{{ networkname }}
    state: directory

# - name: Log into DockerHub
#   become: yes
#   docker_login:
#     username: "{{ Dockerhub_Username }}"
#     password: "{{ Dockerhub_Password }}"    
#     reauthorize: yes

- name: Make router directory
  become: yes
  file:
    path: /etc/containerlab/{{ networkname }}/{{ item }}
    state: directory
  loop:
    - router-WAN
    - router-LAN1
    - router-LAN2
    - router-Internet

- name: Set router WAN files
  become: yes
  copy:
    src: router-WAN/{{ item }}
    dest: /etc/containerlab/{{ networkname }}/router-WAN/{{ item }}
  loop:
    - daemons
    - frr.conf

- name: Set router LAN1 files
  become: yes
  copy:
    src: router-LAN1/{{ item }}
    dest: /etc/containerlab/{{ networkname }}/router-LAN1/{{ item }}
  loop:
    - daemons
    - frr.conf

- name: Set router LAN2 files
  become: yes
  copy:
    src: router-LAN2/{{ item }}
    dest: /etc/containerlab/{{ networkname }}/router-LAN2/{{ item }}
  loop:
    - daemons
    - frr.conf

- name: Set router Internet files
  become: yes
  copy:
    src: router-Internet/{{ item }}
    dest: /etc/containerlab/{{ networkname }}/router-Internet/{{ item }}
  loop:
    - daemons
    - frr.conf

- name: Set SMB Configuration Files
  become: yes
  template:
    src: SMBconf.sh.j2
    dest: /etc/containerlab/{{ networkname }}/SMBconf.sh

- name: Copy DMZsite config
  become: yes
  copy:
    src: DMZsite.conf
    dest: /etc/containerlab/{{ networkname }}/DMZsite.conf

- name: Copy httpsDMZ config
  become: yes
  copy:
    src: httpsDMZsite.conf
    dest: /etc/containerlab/{{ networkname }}/httpsDMZsite.conf
    mode: '0744'

- name: Copy NSD config
  become: yes
  copy:
    src: nsd.conf
    dest: /etc/containerlab/{{ networkname }}/nsd.conf
    mode: 0644

- name: Copy NSD DMZsite config
  become: yes
  copy:
    src: DMZsite.dev.zone
    dest: /etc/containerlab/{{ networkname }}/DMZsite.dev.zone
    mode: 0644

- name: Copy NSD httpsDMZsite config
  become: yes
  copy:
    src: httpsDMZsite.dev.zone
    dest: /etc/containerlab/{{ networkname }}/httpsDMZsite.dev.zone
    mode: 0644

- name: Copy LANweb.sh
  become: yes
  copy:
    src: LANweb.sh
    dest: /etc/containerlab/{{ networkname }}/LANweb.sh
    mode: 0744

- name: Copy WANweb.sh
  become: yes
  copy:
    src: WANweb.sh
    dest: /etc/containerlab/{{ networkname }}/WANweb.sh
    mode: 0744


- name: Configure network topology
  become: yes
  template:
    src: network.yml.j2
    dest: /etc/containerlab/{{ networkname }}/network.yml


- name: Copy ALS_profiles.sh
  become: yes
  template:
    src: ALS_profiles.sh.j2
    dest: /etc/containerlab/{{ networkname }}/ALS_profiles.sh
    mode: 0744
    
